### ISSUE TITLE
import_from_excel() xlsxwriter vs openpyxl

### ISSUE THREAD

**Issue by dwivedilab** [dwivedilab/dlab#1]
The import_from_excel function in io.py requires xlsxwriter to be installed to work properly. However pandas defaults to using openpyxl and as such the end user may confusedly install openpyxl instead of xlsxwriter. Openpyxl cannot write multiple sheets to one excel file and as such will crash. 

This function should be made to be explicitly dependent on xlsxwriter even if both are installed.

**Comment by jselvan** [comment]
Resolved in: 818f7af
